config/routes.rb
Rails.application.routes.draw do

  get '/userdetails', to: 'kioskpages#userdetails'
  get '/userinsurance', to: 'kioskpages#userinsurance'
  get '/userconsent', to: 'kioskpages#userconsent'
  get '/userhealth', to: 'kioskpages#userhealth'
  get '/userdemographics', to: 'kioskpages#userdemographics'


get 'healthinsurance', to: 'healthinsurance#new'
post 'healthinsurances', to: 'healthinsurance#create'
  
  get '/mainapp/:id', to: "kioskpages#mainapp"
  get '/mainapp', to: "kioskpages#mainapp"
  
  get '/signup', to: "kioskpages#signup"
  get "/signin", to: "kioskpages#signin"

  get '/login', to: "kioskqueries#login"
  get '/login', to: "kioskqueries#logout"
  

get 'user/:id', :to => 'users#user_details'
#get '/', :to => 'users#home'

get '/patientDetails', :to => 'patients#patient_details'
get 'intake/:id/personalDetails', :to => 'patients#personalDetails'
get 'intake/:id/insuranceDetails', :to => 'patients#insuranceDetails'
get 'intake/:id/demographicDetails', :to => 'patients#demographicDetails'
get 'intake/:id/blueButton', :to => 'patients#blueButton'

patch 'intake/:id/personalDetails', :to => 'patients#personalDetailsUpdate'
patch 'intake/:id/insuranceDetails', :to => 'patients#insuranceDetailsUpdate'
patch 'intake/:id/demographicDetails', :to => 'patients#demographicDetailsUpdate'
patch 'intake/:id/blueButton', :to => 'patients#blueButtonUpdate'

delete 'intake/:patient_id', :to => 'patients#destroy'

root to: redirect("https://patient-login-main.herokuapp.com/")


  resources :sessions
  resources :patients
  resources :clients
  resources :users
  resources :health_histories
  resources :healthinsurances
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/healthinsurance.rb
class Healthinsurance < ApplicationRecord
  belongs_to :patient
end

app/controllers/healthinsurance_controller.rb
class HealthinsuranceController < ApplicationController
  
  # GET /healthinsurance/new
  def new
  @healthinsurance = Healthinsurance.new
  end
  
  # POST /healthinsurance or /healthinsurance.json
  def create
    @healthinsurance = Healthinsurance.new(user_params)
    if @healthinsurance.save
      session[:healthinsurance] = @healthinsurance.id
      redirect_to root_path, notice: "Successfully saved data"
    else
      render :new
    end
  end
  
# GET /intake/:id/insuranceDetails get patient insurance details
  def insuranceDetails
	#patient = Patient.select(:id,:user_id,:insurance_no,:rx_group,:rx_bin,:rx_pcn, :provider, priority).find(params[:id])
	
	patient = Patient.select(:healthinsurance_id, :insurer_name, :patient_id, :serial_id).find(params[:id])
	render json: {"patient" => patient}, status: :ok
  end

  private

  def user_params  #params.require(:insuranceid).permit(:healthinsurance_id, :insurer_name, :patient_id, :serial_id)
 params.require(:patient).permit(:id,:user_id, :license_no, :sex, :height, :weight,:marital_status, :race, :ethnicity,:income_group,:emergency_contact_number, :emergency_contact_name,:emergency_contact_address,:emergency_contact_email, :rx_group, :rx_bin, :rx_pcn, :blue_button_approval, :visit_detail, :legal_consent, :insurance_no, :provider, :priority, :healthinsurance_id, :insurer_name, :patient_id, :serial_id)
  end

  
end

app/helpers/healthinsurances_helper.rb
module HealthinsurancesHelper
end

app/views/healthinsurance/_form.html.erb
<%= form_with(model: healthinsurance) do |form| %>
  <% if healthinsurance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(healthinsurance.errors.count, "error") %> prohibited this healthinsurance from being saved:</h2>

      <ul>
        <% healthinsurance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :relation %>
    <%= form.text_field :relation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/healthinsurance/edit.html.erb
<h1>Editing Health Insurance</h1>

<%= render 'form', health_insurance: @healthinsurance %>

<%= link_to 'Show', @healthinsurance %> |
<%= link_to 'Back', health_insurances_path %>

app/views/healthinsurance/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Health Insurance</h1>

<table>
  <thead>
    <tr>
      <th>Relation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @healthinsurance.each do |health_insurance| %>
      <tr>
        <td><%= healthinsurance.relation %></td>
        <td><%= link_to 'Show', healthinsurance %></td>
        <td><%= link_to 'Edit', edit_healthinsurance_path(healthinsurance) %></td>
        <td><%= link_to 'Destroy', healthinsurance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Health Insurance', new_healthinsurance_path %>

app/views/healthinsurance/new.html.erb
<h1>New Health Insurance</h1>

<%= render 'form', healthinsurance: @healthinsurance %>

<%= link_to 'Back', healthinsurance_path %>

app/views/healthinsurance/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Relation:</strong>
  <%= @healthinsurance.relation %>
</p>

<%= link_to 'Edit', edit_healthinsurance_path(@healthinsurance) %> |
<%= link_to 'Back', healthinsurance_path %>