config/routes.rb
Rails.application.routes.draw do

  get '/userdetails', to: 'kioskpages#userdetails'
  get '/userinsurance', to: 'kioskpages#userinsurance'
  get '/userconsent', to: 'kioskpages#userconsent'
  get '/userhealth', to: 'kioskpages#userhealth'
  get '/userdemographics', to: 'kioskpages#userdemographics'


get 'healthinsurance', to: 'healthinsurance#new'
post 'healthinsurances', to: 'healthinsurance#create'
  
  get '/mainapp/:id', to: "kioskpages#mainapp"
  get '/mainapp', to: "kioskpages#mainapp"
  
  get '/signup', to: "kioskpages#signup"
  get "/signin", to: "kioskpages#signin"

  get '/login', to: "kioskqueries#login"
  get '/login', to: "kioskqueries#logout"
  

get 'user/:id', :to => 'users#user_details'
#get '/', :to => 'users#home'

get '/patientDetails', :to => 'patients#patient_details'
get 'intake/:id/personalDetails', :to => 'patients#personalDetails'
get 'intake/:id/insuranceDetails', :to => 'patients#insuranceDetails'
get 'intake/:id/demographicDetails', :to => 'patients#demographicDetails'
get 'intake/:id/blueButton', :to => 'patients#blueButton'

patch 'intake/:id/personalDetails', :to => 'patients#personalDetailsUpdate'
patch 'intake/:id/insuranceDetails', :to => 'patients#insuranceDetailsUpdate'
patch 'intake/:id/demographicDetails', :to => 'patients#demographicDetailsUpdate'
patch 'intake/:id/blueButton', :to => 'patients#blueButtonUpdate'

delete 'intake/:patient_id', :to => 'patients#destroy'

root to: redirect("https://patient-login-main.herokuapp.com/")


  resources :sessions
  resources :patients
  resources :clients
  resources :users
  resources :health_histories
  resources :healthinsurances
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/health_history.rb
class HealthHistory < ApplicationRecord
  belongs_to :patients, optional: true
end

app/controllers/health_histories_controller.rb
class HealthHistoriesController < ApplicationController
  before_action :set_health_history, only: %i[ show edit update destroy ]

  # GET /health_histories or /health_histories.json
  def index
    health_histories = HealthHistory.all
    render json: {status: 'Success', message: 'Loaded health histories', health_history: health_histories}, status: :ok
  end

  # GET /health_histories/1 or /health_histories/1.json
  def show
	health_history = HealthHistory.find(params[:id])
	render json: {status: 'Success', message: 'Loaded health history', health_history: health_history}, status: :ok
  end

  # GET /health_histories/new
  def new
    @health_history = HealthHistory.new
  end

  # GET /health_histories/1/edit
  def edit
  end

  # POST /health_histories or /health_histories.json
  def create
    #@health_history = HealthHistory.new(health_history_params)

    #respond_to do |format|
      #if @health_history.save
        #format.html { redirect_to @health_history, notice: "Health history was successfully created." }
        #format.json { render :show, status: :created, location: @health_history }
      #else
        #format.html { render :new, status: :unprocessable_entity }
        #format.json { render json: @health_history.errors, status: :unprocessable_entity }
      #end
    #end
    begin
        HealthHistory.transaction do
            @hh = HealthHistory.create!(health_history_params)
        end
    rescue ActiveRecord::RecordInvalid => exception
        @bands = {
            error: {
                status: 422,
                message: exception
            }
        }
    end
  
        render json: @bands
    end
  
    private
  
    def bands_params
        params.permit(bands: [:name, :year]).require(:bands)
    end

  # PATCH/PUT /health_histories/1 or /health_histories/1.json
  def update
    respond_to do |format|
      if @health_history.update(health_history_params)
        format.html { redirect_to @health_history, notice: "Health history was successfully updated." }
        format.json { render :show, status: :ok, location: @health_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @health_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /health_histories/1 or /health_histories/1.json
  def destroy
    @health_history.destroy
    respond_to do |format|
      format.html { redirect_to health_histories_url, notice: "Health history was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_health_history
      @health_history = HealthHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def health_history_params
params.require(:health_history).permit(:patient_id, :medications, :tetanus, :flu, :zoster, :pnuemovax, :prevnar, :asthma, :cancer, :depression, :diabetes, :heart_disease, :high_blood_pressure, :high_cholesterol, :stroke, :other, :surgeries, :family_medical_history)

    end
end

app/helpers/health_histories_helper.rb
module HealthHistoriesHelper
end

app/views/health_histories/_form.html.erb
<%= form_with(model: health_history) do |form| %>
  <% if health_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(health_history.errors.count, "error") %> prohibited this health_history from being saved:</h2>

      <ul>
        <% health_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= form.label :patient_id %>
    <%= form.number_field :patient_id %>
  </div>
  <div class="field">
    <%= form.label :medications %>
    <%= form.text_field :medications %>
  </div>
<div class="field">
    <%= form.label :tetanus %>
    <%= form.date_select :tetanus %>
  </div>
<div class="field">
    <%= form.label :flu %>
    <%= form.date_select :flu %>
  </div>
<div class="field">
    <%= form.label :zoster %>
    <%= form.date_select :zoster %>
  </div>
<div class="field">
    <%= form.label :pnuemovax %>
    <%= form.date_select :pnuemovax %>
  </div>
<div class="field">
    <%= form.label :prevnar %>
    <%= form.date_select :prevnar %>
  </div>
<div class="field">
    <%= form.label :asthma %>
    <%= form.check_box :asthma %>
  </div>
<div class="field">
    <%= form.label :cancer %>
    <%= form.check_box :cancer %>
  </div>
<div class="field">
    <%= form.label :depression %>
    <%= form.check_box :depression %>
  </div>
<div class="field">
    <%= form.label :diabetes %>
    <%= form.check_box :diabetes %>
  </div>
<div class="field">
    <%= form.label :heart_disease %>
    <%= form.check_box :heart_disease %>
  </div>
<div class="field">
    <%= form.label :high_blood_pressure %>
    <%= form.check_box :high_blood_pressure %>
  </div>
<div class="field">
    <%= form.label :high_cholesterol %>
    <%= form.check_box :high_cholesterol %>
  </div>
<div class="field">
    <%= form.label :stroke %>
    <%= form.check_box :stroke %>
  </div>
<div class="field">
    <%= form.label :other %>
    <%= form.text_field :other %>
  </div>
<div class="field">
    <%= form.label :surgeries %>
    <%= form.text_field :surgeries %>
  </div>
<div class="field">
    <%= form.label :family_medical_history %>
    <%= form.text_field :family_medical_history %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/health_histories/edit.html.erb
<h1>Editing Health History</h1>

<%= render 'form', health_history: @health_history %>

<%= link_to 'Show', @health_history %> |
<%= link_to 'Back', health_histories_path %>

app/views/health_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Health Histories</h1>

<table>
  <thead>
    <tr>
      <th>Relation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @health_histories.each do |health_history| %>
      <tr>
        <td><%= health_history.id %></td>
        <td><%= health_history.patient_id %></td>
        <td><%= link_to 'Show', health_history %></td>
        <td><%= link_to 'Edit', edit_health_history_path(health_history) %></td>
        <td><%= link_to 'Destroy', health_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Health History', new_health_history_path %>

app/views/health_histories/new.html.erb
<h1>New Health History</h1>

<%= render 'form', health_history: @health_history %>

<%= link_to 'Back', health_histories_path %>

app/views/health_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Relation:</strong>
  <%= @health_history.id %>
  <%= @health_history.patient_id %>

</p>

<%= link_to 'Edit', edit_health_history_path(@health_history) %> |
<%= link_to 'Back', health_histories_path %>